spring:
  application:
    name: car-api
  datasource:
    url: jdbc:mysql://localhost:3306/carrental?useSSL=false&characterEncoding=UTF-8
    username: root
    password: mysql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
